version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: security
    restart: unless-stopped
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: security
      POSTGRES_PASSWORD: 123456
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory_network

volumes:
  postgres_data:

networks:
  inventory_network:
    driver: bridge